#!/bin/bash
#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

echo "go command before removing ldflags: $@"

cmd=""

#cycle through all args
for (( i=1; i<=$#; i++ )); do
   eval arg=\$$i
   if [ "$arg" == "-ldflags" ];
   then
   (( i++ ))
   else
   cmd+="$arg "
   fi
done

echo "go command after removing ldflags: $cmd"

/opt/go/bin/go $cmd
