#!/bin/bash
#
# Copyright SecureKey Technologies Inc.
# This file contains software code that is the intellectual property of SecureKey.
# SecureKey reserves all rights in the code and you may not use it without written permission from SecureKey.
#

echo "go command before removing ldflags: $@"

cmd=""

#cycle through all args
for (( i=1; i<=$#; i++ )); do
   eval arg=\$$i
   if [ "$arg" == "-ldflags" ];
   then
   (( i++ ))
   else
   cmd+="$arg "
   fi
done

echo "go command after removing ldflags: $cmd"

/opt/go/bin/go $cmd
